// for the database
const Datastore = require ( 'nedb' );
const myDB = new Datastore ( 'database.db' );

// for the front end
var express = require ( 'express' );
var app = express();

var port = process.env.PORT || 3000;
var server = app.listen ( port );
app.use ( express.static ( 'public' ) );          // use files in public folder
var socket = require ( 'socket.io' );
var io = socket ( server );      

// wait until the database is loaded
myDB.loadDatabase( function ( err ) {
    io.sockets.on ( 'connection', newConnection );
});

// when there is a new connection this function is called
function newConnection ( socket ) {
    
    // first send all data to the new client
    myDB.find ( {}, function ( err, docs ) {
        socket.emit ( 'heresData', docs );
    });

    // if anybody added a new pin, send new pin data to everyone and instert it into the db
    socket.on ( 'newPin', function ( data ) {

        myDB.insert ( data );

        // calling find to also send the id generated by nedb
        myDB.find ( { lat: data.lat, lng: data.lng, color: data.color, text: data.text }, function ( err, docs ) {
            
            // tell everyone there is a new pin
            socket.broadcast.emit ( 'newPin', docs[0] );
            socket.emit ( 'newPin', docs[0] );
            // notify everyone else that someone added a new pin
            socket.broadcast.emit ( 'notify', docs[0] ); 
        });
    });

    // if anyone deleted a pin, tell everyone that pin has been deleted and remove it from the database
    socket.on ( 'deleted', function ( data ) {

        // remove pin from the database
        myDB.remove ({ _id: data },{}, function ( err, numRemoved ) {} );
        // tell everyone which pin was deleted
        socket.broadcast.emit ( 'deleted', data );
        socket.emit ( 'deleted', data );
    });
}